---
- name: Install VLC via Chocolatey on localhost
  hosts: localhost
  connection: local
  tasks:
    - name: Install VLC using Chocolatey
      win_chocolatey:
        name: vlc
        state: latest
